CREATE DATABASE IF NOT EXISTS yourDB;
USE yourDB;
CREATE TABLE waitingRoom(
	id INT AUTO_INCREMENT PRIMARY KEY,
    account VARCHAR(50) NOT NULL UNIQUE,
    deck JSON,
    enteredAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);